#include "gpiocfg.h"

struct GPIODef {
  const std::string func;
  const std::string GPIOx;
  const bool splitpull;
  const bool splitio;
  const std::vector<GPIO_InitTypeDef> GPIOcfg;
};

const std::vector<GPIODef> GPIOSetup = {
    {
        "LinoTT",
        "GPIOC",
        true,
        true,
        {
          (GPIO_InitTypeDef){
            COL0_Pin|COL1_Pin|COL2_Pin|COL3_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_NOPULL,
            0
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_PULLUP,
            0
          },
          (GPIO_InitTypeDef){
            USB_P_Pin|US_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
        }
    },
    {
        "LinoTF",
        "GPIOC",
        true,
        false,
        {
          (GPIO_InitTypeDef){
            COL0_Pin|COL1_Pin|COL2_Pin|COL3_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_NOPULL,
            0
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_PULLUP,
            0
          },
          (GPIO_InitTypeDef){
            USB_P_Pin|US_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
        }
    },
    {
        "LinoFT",
        "GPIOC",
        false,
        true,
        {
          (GPIO_InitTypeDef){
            COL0_Pin|COL1_Pin|COL2_Pin|COL3_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_NOPULL,
            0
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_PULLUP,
            0
          },
          (GPIO_InitTypeDef){
            USB_P_Pin|US_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
        }
    },
    {
        "LinoFF",
        "GPIOC",
        false,
        false,
        {
          (GPIO_InitTypeDef){
            COL0_Pin|COL1_Pin|COL2_Pin|COL3_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_NOPULL,
            0
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_PULLUP,
            0
          },
          (GPIO_InitTypeDef){
            USB_P_Pin|US_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
        }
    },
    {
        "Tano",
        "GPIOA",
        false,
        false,
        {
          (GPIO_InitTypeDef){
            COL0_Pin|COL1_Pin|COL2_Pin|COL3_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_NOPULL,
            0
          },
          (GPIO_InitTypeDef){
            ROW0_Pin|ROW1_Pin,
            GPIO_MODE_INPUT,
            GPIO_PULLUP,
            0
          },
          (GPIO_InitTypeDef){
            USB_P_Pin|US_Pin,
            GPIO_MODE_OUTPUT_PP,
            0,
            GPIO_SPEED_LOW
          },
        }
    },
};
